# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171-q-vpnt_lxSE-NNLZuKNBrOXXWCLj-
"""

l=[1,2,3,4,5,6,7,8,9,10]
print("Original list:",l)
print("Extracted first five elements:",end="")
slc=l[0:5]
print(slc)
print("Reversed extracted elements:",end="")
print(slc[-5:0:1])