# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171-q-vpnt_lxSE-NNLZuKNBrOXXWCLj-
"""

dic={"Alice":85,"A":100}
name=input("Enter the student's name:")
if name in dic:
    print(name,"'s marks:","=",dic[name])
else:
    print("Student not found")
